#!/bin/bash
#
# Elasticsearch - this script starts and stops the redis-server daemon
#
# chkconfig:  - 80 12
# description: Elasticsearch is a database
# processname: Elasticsearch
 
source /etc/init.d/functions
 
BIN="$ES_HOME/bin"
PIDFILE="$BIN/es.pid"
 
 
### Read configuration
[ -r "$SYSCONFIG" ] && source "$SYSCONFIG"
 
RETVAL=0
prog="elasticsearch"
desc="Elasticsearch Server"
 
start() {
 
    if [ -e $PIDFILE ];then
       echo "$desc already running...."
       exit 1
    fi
 
    echo -n $"Starting $desc: "
    daemon su -- $USER $BIN/$prog -d -p $PIDFILE

 
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && touch /var/lock/subsys/$prog
    return $RETVAL
}
 
stop() {
    echo -n $"Stop $desc: "
    killproc -p $PIDFILE
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/$prog $PIDFILE
    return $RETVAL
}
 
restart() {
  stop
  start
}
 
case "$1" in
 start)
    start
    ;;
 stop)
    stop
    ;;
 restart)
    restart
    ;;
 condrestart)
    [ -e /var/lock/subsys/$prog ] && restart
    RETVAL=$?
    ;;
 status)
    status $prog
    RETVAL=$?
    ;;
  *)
    echo $"Usage: $0 {start|stop|restart|condrestart|status}"
    RETVAL=1
esac
 
exit $RETVAL

